extends: google
globals:
  goog: false
env:
  browser: true
parserOptions:
  ecmaVersion: 2015
  sourceType: module
rules:
  indent: [error, 2]
  max-len: [error, 120]
  no-new: warn
  quotes: [error, single, {"avoidEscape": true, "allowTemplateLiterals": true}]
  no-var: error
  curly: error
  no-floating-decimal: error
  prefer-const: error
  require-jsdoc: off
  valid-jsdoc: off
